# Generated by Django 3.2.10 on 2021-12-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_given', models.BooleanField(default=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lottos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_tickets', models.IntegerField()),
                ('available_tickets', models.IntegerField(blank=True, null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('ip_addresses', models.TextField(default='0.0.0.0,')),
                ('winners_drawn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField()),
                ('vertification_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prizesss', to='appSix.prizesingle')),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottotickets', to='appSix.lottos')),
            ],
        ),
        migrations.AddField(
            model_name='prizesingle',
            name='lotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotto_prizes', to='appSix.lottos'),
        ),
        migrations.CreateModel(
            name='Prizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='appSix.lottos')),
            ],
        ),
    ]
